# Generated by Django 5.2.8 on 2025-11-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('zona_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Origen')),
                ('zona_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Destino')),
                ('estado_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Nuevo')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
