# Generated by Django 5.2.8 on 2025-11-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='zona_destino',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='zona_origen',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('cambio_estado', 'Cambio de Estado')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='activos.ubicacion', verbose_name='Ubicación Destino'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='activos.ubicacion', verbose_name='Ubicación Origen'),
        ),
    ]
