# Generated by Django 5.2.8 on 2025-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_articulo_remove_activo_categoria_activo_articulo_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='ubicacion_destino',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='ubicacion_origen',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='zona_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Destino'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='zona_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Origen'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
