# Generated by Django 5.2.8 on 2025-12-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_remove_activo_articulo_fk_remove_movimiento_activo_and_more'),
    ]

    operations = [
        # Primero renombrar el campo marca existente a marca_old
        migrations.RenameField(
            model_name='activo',
            old_name='marca',
            new_name='marca_old',
        ),
        # Crear el modelo Marca
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='activos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'unique_together': {('nombre', 'categoria')},
            },
        ),
        # Agregar el nuevo campo marca como ForeignKey
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.marca', verbose_name='MARCA'),
        ),
    ]
