# Generated by Django on 2025-12-03

from django.db import migrations


def migrate_marcas_data(apps, schema_editor):
    """
    Crear categoría por defecto, crear marcas y asociar activos existentes.
    """
    Activo = apps.get_model('activos', 'Activo')
    Categoria = apps.get_model('activos', 'Categoria')
    Marca = apps.get_model('activos', 'Marca')
    
    # Crear o obtener categoría por defecto
    categoria_default, created = Categoria.objects.get_or_create(
        nombre='Dispositivos',
        defaults={'descripcion': 'Categoría por defecto para dispositivos'}
    )
    
    # Marcas existentes que estaban hardcodeadas
    marcas_map = {}
    marcas_existentes = [
        'SUNMI V1',
        'SUNMI V2',
        'SUNMI V2 PRO',
        'N910',
        'NEWLAND GRIS',
    ]
    
    # Crear las marcas en el nuevo modelo
    for nombre_marca in marcas_existentes:
        marca, created = Marca.objects.get_or_create(
            nombre=nombre_marca,
            categoria=categoria_default,
            defaults={'descripcion': f'Marca {nombre_marca}'}
        )
        marcas_map[nombre_marca] = marca
    
    # Migrar los activos existentes
    for activo in Activo.objects.all():
        if activo.marca_old and activo.marca_old in marcas_map:
            activo.marca = marcas_map[activo.marca_old]
            activo.save(update_fields=['marca'])


def reverse_migrate(apps, schema_editor):
    """
    Reversión de la migración.
    """
    Activo = apps.get_model('activos', 'Activo')
    Marca = apps.get_model('activos', 'Marca')
    Categoria = apps.get_model('activos', 'Categoria')
    
    # Limpiar las referencias de marca en activos
    Activo.objects.all().update(marca=None)
    
    # Eliminar las marcas creadas
    Marca.objects.filter(categoria__nombre='Dispositivos').delete()
    
    # Eliminar la categoría si no tiene otras marcas
    try:
        categoria = Categoria.objects.get(nombre='Dispositivos')
        if not categoria.marcas.exists():
            categoria.delete()
    except Categoria.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_activo_marca_old_marca_alter_activo_marca'),
    ]

    operations = [
        migrations.RunPython(migrate_marcas_data, reverse_migrate),
    ]
