# Generated by Django 5.2.8 on 2025-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_alter_tranzabilidad_activo_alter_tranzabilidad_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='zona',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
