# Generated by Django 5.2.8 on 2026-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_remove_zona_descripcion_zona_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Centro de Costo')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['nombre'],
            },
        ),
    ]
