# Generated by Django 5.2.8 on 2026-01-20 14:48

from django.db import migrations

def populate_centro_costo(apps, schema_editor):
    CentroCosto = apps.get_model('activos', 'CentroCosto')
    
    data = [
        ("6972", "AGUACHICA MORROSCOY"),
        ("8561", "AGUACHICA SAN ANTONIO"),
        ("8560", "AGUACHICA SAN EDUARDO"),
        ("8562", "AGUACHICA SAN ROQUE"),
        ("6973", "ASTREA"),
        ("6974", "BECERRIL"),
        ("6975", "BOSCONIA"),
        ("20329", "CASACARA CODAZZI"),
        ("6976", "CHIMICHAGUA"),
        ("6977", "CHIRIGUANA"),
        ("6978", "CODAZZI"),
        ("6979", "CURUMANI"),
        ("6980", "EL COPEY"),
        ("6981", "EL PASO"),
        ("6982", "GAMARRA"),
        ("6983", "GONZALEZ"),
        ("6984", "LA GLORIA"),
        ("6985", "LA JAGUA"),
        ("6986", "LA LOMA"),
        ("6988", "LA_PAZ"),
        ("6989", "MANAURE"),
        ("45388", "NUEVO BOSCONIA"),
        ("42463", "NUEVO CODAZZI"),
        ("6990", "PAILITAS"),
        ("6991", "PELAYA"),
        ("6993", "PUEBLOBELLO"),
        ("6994", "RIO DE ORO"),
        ("6996", "SAN ALBERTO"),
        ("6997", "SAN DIEGO"),
        ("44806", "SAN JOSE DE ORIENTE - LA PAZ"),
        ("6998", "SAN MARTIN"),
        ("44808", "SAN ROQUE - CURUMANI"),
        ("6999", "TAMALAMEQUE"),
        ("24041", "VALLEDUPAR AMBULANTE"),
        ("9206", "VALLEDUPAR AV LOS MILITARES"),
        ("17191", "VALLEDUPAR BELLA VISTA"),
        ("8552", "VALLEDUPAR FUNDADORES"),
        ("8558", "VALLEDUPAR LA CANDELARIA"),
        ("17176", "VALLEDUPAR LA CUARTA"),
        ("8553", "VALLEDUPAR LANEVADA"),
        ("8556", "VALLEDUPAR LOPERENA"),
        ("43654", "VALLEDUPAR ORBICENTRO"),
        ("18935", "VALLEDUPAR PEDIATRICO"),
        ("7001", "VALLEDUPAR PRINCIPAL"),
        ("23794", "VALLEDUPAR SIERRA NEVADA"),
        ("18936", "VALLEDUPAR SIMON BOLIVAR 7D"),
        ("8554", "VALLEDUPAR TERMINAL"),
        ("45386", "VALLEDUPAR TERMINAL 2"),
        ("11111", "EMBAJADORA MOVIL APP"),
        ("22222", "VENDEDOR AMBULANTE"),
        ("33333", "RECAUDADORES"),
        ("44444", "EMBAJADOR BETPLAY"),
        ("55555", "TAT"),
    ]
    
    for codigo, nombre in data:
        CentroCosto.objects.get_or_create(codigo=codigo, defaults={'nombre': nombre})

def reverse_populate_centro_costo(apps, schema_editor):
    CentroCosto = apps.get_model('activos', 'CentroCosto')
    CentroCosto.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_centrocosto'),
    ]

    operations = [
        migrations.RunPython(populate_centro_costo, reverse_populate_centro_costo),
    ]
