# Generated by Django 5.2.8 on 2026-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_restructure_zonas_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='zona',
            name='codigo',
            field=models.CharField(default='DEFAULT_CODE', max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
