# Generated by Django 5.2.8 on 2026-01-20 20:07

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """Poblar datos iniciales de Zonas, Categorías y Marcas"""
    Zona = apps.get_model('activos', 'Zona')
    Categoria = apps.get_model('activos', 'Categoria')
    Marca = apps.get_model('activos', 'Marca')
    
    # Datos de Zonas
    zonas_data = [
        {'codigo': '6972', 'nombre': 'AGUACHICA MORROSCOY'},
        {'codigo': '8561', 'nombre': 'AGUACHICA SAN ANTONIO'},
        {'codigo': '8560', 'nombre': 'AGUACHICA SAN EDUARDO'},
        {'codigo': '8562', 'nombre': 'AGUACHICA SAN ROQUE'},
        {'codigo': '77777', 'nombre': 'ALMACEN'},
        {'codigo': '6973', 'nombre': 'ASTREA'},
        {'codigo': '6974', 'nombre': 'BECERRIL'},
        {'codigo': '6975', 'nombre': 'BOSCONIA'},
        {'codigo': '20329', 'nombre': 'CASACARA CODAZZI'},
        {'codigo': '6976', 'nombre': 'CHIMICHAGUA'},
        {'codigo': '6977', 'nombre': 'CHIRIGUANA'},
        {'codigo': '6978', 'nombre': 'CODAZZI'},
        {'codigo': '6979', 'nombre': 'CURUMANI'},
        {'codigo': '6980', 'nombre': 'EL COPEY'},
        {'codigo': '6981', 'nombre': 'EL PASO'},
        {'codigo': '44444', 'nombre': 'EMBAJADOR BETPLAY'},
        {'codigo': '11111', 'nombre': 'EMBAJADORA MOVIL APP'},
        {'codigo': '6982', 'nombre': 'GAMARRA'},
        {'codigo': '6983', 'nombre': 'GONZALEZ'},
        {'codigo': '6984', 'nombre': 'LA GLORIA'},
        {'codigo': '6985', 'nombre': 'LA JAGUA'},
        {'codigo': '6986', 'nombre': 'LA LOMA'},
        {'codigo': '6988', 'nombre': 'LA_PAZ'},
        {'codigo': '6989', 'nombre': 'MANAURE'},
        {'codigo': '45388', 'nombre': 'NUEVO BOSCONIA'},
        {'codigo': '42463', 'nombre': 'NUEVO CODAZZI'},
        {'codigo': '6990', 'nombre': 'PAILITAS'},
        {'codigo': '6991', 'nombre': 'PELAYA'},
        {'codigo': '6993', 'nombre': 'PUEBLOBELLO'},
        {'codigo': '33333', 'nombre': 'RECAUDADORES'},
        {'codigo': '6994', 'nombre': 'RIO DE ORO'},
        {'codigo': '6996', 'nombre': 'SAN ALBERTO'},
        {'codigo': '6997', 'nombre': 'SAN DIEGO'},
        {'codigo': '44806', 'nombre': 'SAN JOSE DE ORIENTE - LA PAZ'},
        {'codigo': '6998', 'nombre': 'SAN MARTIN'},
        {'codigo': '44808', 'nombre': 'SAN ROQUE - CURUMANI'},
        {'codigo': '6999', 'nombre': 'TAMALAMEQUE'},
        {'codigo': '55555', 'nombre': 'TAT'},
        {'codigo': '88888', 'nombre': 'TIC 17'},
        {'codigo': '66666', 'nombre': 'VALLEDUPAR'},
        {'codigo': '22222', 'nombre': 'VENDEDOR AMBULANTE'},
    ]
    
    # Crear zonas solo si no existen
    for zona_data in zonas_data:
        Zona.objects.get_or_create(
            codigo=zona_data['codigo'],
            defaults={'nombre': zona_data['nombre']}
        )
    
    # Crear categoría MAQUINAS
    categoria_maquinas, created = Categoria.objects.get_or_create(
        nombre='MAQUINAS',
        defaults={'descripcion': 'Máquinas POS y dispositivos de punto de venta'}
    )
    
    # Datos de Marcas
    marcas_data = [
        'SUNMI V1',
        'SUNMI V2',
        'SUNMI V2 PRO',
        'N910',
        'N910 GRIS',
    ]
    
    # Crear marcas solo si no existen
    for marca_nombre in marcas_data:
        Marca.objects.get_or_create(
            nombre=marca_nombre,
            categoria=categoria_maquinas
        )


def reverse_populate(apps, schema_editor):
    """Revertir la población de datos (opcional)"""
    # No eliminamos datos en reverse para evitar pérdida de información
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_refine_zona_schema'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate),
    ]
